### ISSUE TITLE
Pull plotly from CDN instead of inlining whole javascript into notebook file

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyter-renderers#105]
This makes the notebook file much larger than it needs to be, is it possible to just pull plotly.js from the plotly CDN and inject like bokeh does (https://github.com/bokeh/jupyterlab_bokeh/blob/master/src/renderer.ts#L39)

**Comment by gnestor** [comment]
There is no inline Javascript being inserted into notebook files. Currently (due to issues with plotly.js and JupyterLab extensions not having full control over webpack config), `plotly.min.js` text content is being imported and injected into a script tag in the document head. In the future, we would like to just import it like we do with almost every other library.

**Comment by timkpaine** [comment]
is this new? this is what I see:
![plotly](https://user-images.githubusercontent.com/3105306/36760329-5be88606-1be8-11e8-90cc-67c33c9f87a2.gif)

**Comment by timkpaine** [comment]
yeah I see it here, let me update and check
https://github.com/jupyterlab/jupyter-renderers/blob/master/packages/plotly-extension/src/index.tsx#L32

**Comment by gnestor** [comment]
What you're seeing there is the result of calling [`plotly.offline. init_notebook_mode(connected=False)` method](https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L129) from the plotly python library. This method doesn't work in JupyterLab because JupyterLab does not evaluate inline Javascript in outputs like classic notebook did. Just leave out that call in JupyterLab and you're outputs should be very lean 👍

**Comment by timkpaine** [comment]
@gnestor ah excellent, thanks!
