### ISSUE TITLE
How do these work?

### ISSUE THREAD

**Issue by sglyon** [jupyterlab/jupyter-renderers#16]
I manage the plotly Julia packages and would love to have support for my figures in jupyterlab.

I was hoping that I could just add a JSON object containing the plotly data and layout with the mime type `application/vnd.plotly.v1+json` to the outputs I send to the Julia jupyter kernel and that this extension would pick it up, but that doesn't seem to happen.

This is what I do to get support inside nteract and it works well.

Is there an example of what the output needs to be in order to render my plotly figures in a notebook backed by my Julia kernel?

**Comment by gnestor** [comment]
The plotly extension was broken due to https://github.com/jupyterlab/jupyter-renderers/issues/10. I just published 0.8.1 version of @jupyterlab/plotly-extension, so once you upgrade it should work as expected. The kernel will need to return a [`display_data` message](http://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data) so you will need to be sure to call the equivalent to `IPython.display`.

Let me know if you have anymore issues. If it works, feel free to close.

**Comment by sglyon** [comment]
Great, thanks!
