### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by aliasmrchips** [jupyterlab/jupyter-renderers#23]
I followed the instructions to run jupyter lab in development mode from here: https://github.com/aliasmrchips/jupyterlab/blob/master/CONTRIBUTING.md and likewise for jupyter-renderers. Everything seems to be installed correctly and when I start jupyter lab I see:
```
Known labextensions:
   app dir: /home/aliasmrchips/miniconda3/share/jupyter/lab
        @jupyterlab/geojson-extension@0.9.2  enabled  OK
        @jupyterlab/plotly-extension@0.9.2  enabled  OK
   linked extensions:
        @jupyterlab/geojson-extension: /home/aliasmrchips/jupyterlab/jupyter-renderers/packages/geojson-extension
        @jupyterlab/plotly-extension: /home/aliasmrchips/jupyterlab/jupyter-renderers/packages/plotly-extension
```
However, if I go to open a geojson file from jupyter lab, it just opens in a regular text editor. If I right click, there is no additional open option. Am I missing something?

**Comment by blink1073** [comment]
Hi @aliasmrchips, third party extensions are not used in development mode because of the way the mono-repo works.  You can use the `addsibling` approach mentioned [here](https://github.com/jupyterlab/jupyterlab/blob/4cc633e6670cc13e1724f5c666376aba2364458e/docs/extensions_dev.md#extension-authoring) to install an extension in dev mode.

**Comment by aliasmrchips** [comment]
Thanks! If I can develop the extensions separately, I don't think I need to run jupyter lab in dev mode also.
